name: Deploy Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda_function.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Empaquetar Lambda
        run: zip function.zip lambda_function.py

      - name: Desplegar a AWS Lambda
        run: aws lambda update-function-code --function-name notas-cloud-backend --zip-file fileb://function.zip